"""
Django settings for iwantmore project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import pymysql

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SITE_ID = 1


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')


SECRET_KEY = 'django-insecure-*_-(f=pde*x4&myae7vc74#p=&8&k66!iqhk=a2l^7^g^aime_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'iwm',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'iwantmore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iwantmore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db',
        'USER': 'root',
        'PASSWORD': 'Badhon',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
LOGIN_URL = '/login/'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # default
    'allauth.account.auth_backends.AuthenticationBackend',
)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID'),
            'secret': config('GOOGLE_CLIENT_SECRET'),
        },
    }
}
SOCIALACCOUNT_PROVIDERS.update({
    'facebook': {
        'APP': {
            'client_id': config('FACEBOOK_CLIENT_ID'),
            'secret': config('FACEBOOK_CLIENT_SECRET'),
        },
    }
})

# ========================
# django-allauth configuration
# ========================
# You should set these environment variables in your .env or system environment:
# - GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET
# - FACEBOOK_CLIENT_ID, FACEBOOK_CLIENT_SECRET
# The values above are used by the socialaccount providers. If you prefer,
# you can also create SocialApp entries in Django admin (recommended for multiple
# environments). See the instructions below.

SOCIALACCOUNT_LOGIN_ON_GET=True

# Basic allauth settings - adjust as needed
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # can be 'mandatory' in production
ACCOUNT_USERNAME_REQUIRED = True
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Socialaccount settings - optional custom scopes, can be tuned per provider
SOCIALACCOUNT_PROVIDERS.setdefault('google', {})
SOCIALACCOUNT_PROVIDERS['google'].setdefault('SCOPE', ['profile', 'email'])
SOCIALACCOUNT_PROVIDERS['google'].setdefault('AUTH_PARAMS', {'access_type': 'online'})

SOCIALACCOUNT_PROVIDERS.setdefault('facebook', {})
SOCIALACCOUNT_PROVIDERS['facebook'].setdefault('METHOD', 'oauth2')
SOCIALACCOUNT_PROVIDERS['facebook'].setdefault('SCOPE', ['email', 'public_profile'])

# Important: After adding the provider credentials either via environment or
# via the Django admin (SocialApp), open Django admin -> Social applications ->
# Add SocialApp (choose provider google/facebook), set client id & secret, and
# set the Sites (select your site, e.g., example.com or 127.0.0.1:8000) so
# Django-allauth can match the site. You must also register the correct
# redirect/callback URL(s) in the provider developer console:
#
# Google: Authorized redirect URI -> http://127.0.0.1:8000/accounts/google/login/callback/
# Facebook: Valid OAuth Redirect URI -> http://127.0.0.1:8000/accounts/facebook/login/callback/




# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ========================
# SSLCOMMERZ Configuration
# ========================

# Sandbox credentials (for testing)
SSLCOMMERZ_STORE_ID = "testbox"
SSLCOMMERZ_STORE_PASSWD = "qwerty"

# Gateway URLs
if DEBUG:  # sandbox mode
    SSLCOMMERZ_API_URL = "https://sandbox.sslcommerz.com/gwprocess/v4/api.php"
    SSLCOMMERZ_VALIDATION_URL = "https://sandbox.sslcommerz.com/validator/api/validationserverAPI.php"
else:  # production mode
    SSLCOMMERZ_API_URL = "https://securepay.sslcommerz.com/gwprocess/v4/api.php"
    SSLCOMMERZ_VALIDATION_URL = "https://securepay.sslcommerz.com/validator/api/validationserverAPI.php"

# Your site callback URLs
SSLCOMMERZ_SUCCESS_URL = "http://127.0.0.1:8000/sslcommerz/success/"
SSLCOMMERZ_FAIL_URL = "http://127.0.0.1:8000/sslcommerz/fail/"
SSLCOMMERZ_CANCEL_URL = "http://127.0.0.1:8000/sslcommerz/cancel/"