"""
Django settings for iwantmore project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import pymysql

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SITE_ID = 1


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')


SECRET_KEY = 'django-insecure-*_-(f=pde*x4&myae7vc74#p=&8&k66!iqhk=a2l^7^g^aime_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'import_export',  # For CSV/Excel exports
    'auditlog',  # For audit logging
    'iwm',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'iwantmore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iwantmore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db',
        'USER': 'root',
        'PASSWORD': 'Badhon',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
LOGIN_URL = '/login/'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # default
    'allauth.account.auth_backends.AuthenticationBackend',
)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID'),
            'secret': config('GOOGLE_CLIENT_SECRET'),
        },
    }
}
SOCIALACCOUNT_PROVIDERS.update({
    'facebook': {
        'APP': {
            'client_id': config('FACEBOOK_CLIENT_ID'),
            'secret': config('FACEBOOK_CLIENT_SECRET'),
        },
    }
})

# ========================
# django-allauth configuration
# ========================
# You should set these environment variables in your .env or system environment:
# - GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET
# - FACEBOOK_CLIENT_ID, FACEBOOK_CLIENT_SECRET
# The values above are used by the socialaccount providers. If you prefer,
# you can also create SocialApp entries in Django admin (recommended for multiple
# environments). See the instructions below.

SOCIALACCOUNT_LOGIN_ON_GET=True

# Basic allauth settings - adjust as needed
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "optional"  # can be 'mandatory' in production
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Socialaccount settings - optional custom scopes, can be tuned per provider
SOCIALACCOUNT_PROVIDERS.setdefault('google', {})
SOCIALACCOUNT_PROVIDERS['google'].setdefault('SCOPE', ['profile', 'email'])
SOCIALACCOUNT_PROVIDERS['google'].setdefault('AUTH_PARAMS', {'access_type': 'online'})

SOCIALACCOUNT_PROVIDERS.setdefault('facebook', {})
SOCIALACCOUNT_PROVIDERS['facebook'].setdefault('METHOD', 'oauth2')
SOCIALACCOUNT_PROVIDERS['facebook'].setdefault('SCOPE', ['email', 'public_profile'])

# Important: After adding the provider credentials either via environment or
# via the Django admin (SocialApp), open Django admin -> Social applications ->
# Add SocialApp (choose provider google/facebook), set client id & secret, and
# set the Sites (select your site, e.g., example.com or 127.0.0.1:8000) so
# Django-allauth can match the site. You must also register the correct
# redirect/callback URL(s) in the provider developer console:
#
# Google: Authorized redirect URI -> http://127.0.0.1:8000/accounts/google/login/callback/
# Facebook: Valid OAuth Redirect URI -> http://127.0.0.1:8000/accounts/facebook/login/callback/




# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========================
# JAZZMIN ADMIN THEME CONFIGURATION
# ========================
JAZZMIN_SETTINGS = {
    "site_title": "I Want More Admin",
    "site_header": "I Want More",
    "site_brand": "IWM Dashboard",
    "site_logo": "/imgs/iwm.png",
    "welcome_sign": "Welcome to I Want More Admin Dashboard",
    "copyright": "I Want More © 2026",
    "search_model": "iwm.Product",
    
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Top navbar color
    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
        {"name": "Products", "url": "/admin/iwm/product/", "permissions": ["iwm.view_product"]},
        {"name": "Orders", "url": "/admin/iwm/order/", "permissions": ["iwm.view_order"]},
    ],
    
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "iwm.Product": "fas fa-shopping-bag",
        "iwm.Category": "fas fa-list",
        "iwm.Order": "fas fa-receipt",
        "iwm.NewsletterSubscriber": "fas fa-envelope",
        "iwm.Review": "fas fa-star",
    },
    
    "default_icon_parent": "fas fa-chevron-right",
    "default_icon_children": "fas fa-arrow-right",
    
    "theme": "lux",  # Premium light theme with professional look
    "dark_mode_theme": "darkly",
    
    "show_ui_builder": False,
    
    "navigation": [
        {
            "title": "Dashboard",
            "icon": "fas fa-home",
            "children": [],
        },
        {
            "title": "E-Commerce",
            "icon": "fas fa-shopping-cart",
            "children": [
                {
                    "name": "Products",
                    "url": "admin:iwm_product_changelist",
                    "icon": "fas fa-shopping-bag",
                    "permissions": ["iwm.view_product"]
                },
                {
                    "name": "Categories",
                    "url": "admin:iwm_category_changelist",
                    "icon": "fas fa-list",
                    "permissions": ["iwm.view_category"]
                },
                {
                    "name": "Orders",
                    "url": "admin:iwm_order_changelist",
                    "icon": "fas fa-receipt",
                    "permissions": ["iwm.view_order"]
                },
                {
                    "name": "Coupons",
                    "url": "admin:iwm_coupon_changelist",
                    "icon": "fas fa-ticket-alt",
                    "permissions": ["iwm.view_coupon"]
                },
            ],
        },
        {
            "title": "Marketing",
            "icon": "fas fa-bullhorn",
            "children": [
                {
                    "name": "Newsletter",
                    "url": "admin:iwm_newslettersubscriber_changelist",
                    "icon": "fas fa-envelope",
                    "permissions": ["iwm.view_newslettersubscriber"]
                },
                {
                    "name": "Reviews",
                    "url": "admin:iwm_review_changelist",
                    "icon": "fas fa-star",
                    "permissions": ["iwm.view_review"]
                },
            ],
        },
        {
            "title": "User Management",
            "icon": "fas fa-users",
            "children": [
                {
                    "name": "Users",
                    "url": "admin:auth_user_changelist",
                    "icon": "fas fa-user",
                    "permissions": ["auth.view_user"]
                },
                {
                    "name": "Addresses",
                    "url": "admin:iwm_address_changelist",
                    "icon": "fas fa-map-marker-alt",
                    "permissions": ["iwm.view_address"]
                },
            ],
        },
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "brand_small": False,
    "brand_colour": "#ff6f91",  # IWM Pink brand color
    "accent": "accent-primary",
    "navbar": "navbar-light",  # Light navbar
    "sidebar": "sidebar-light-primary",  # Light sidebar
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "lux",
    "dark_mode": False,  # Light mode by default
    "dark_mode_force": False,
}

# ========================
# CKEDITOR CONFIGURATION
# ========================
CKEDITOR_UPLOAD_PATH = "ckeditor_uploads/"
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_ALLOW_NONIMAGE_FILES = False

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', '-', 'Templates']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms', 'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField']},
            '/',
            {'name': 'basicstyles', 'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph', 'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert', 'items': ['Image', 'Flash', 'Table', '-', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
        ],
        'toolbar': 'YourCustomToolbarConfig',
        'height': 291,
        'width': '100%',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
        'toolbarCanCollapse': True,
        'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}

# ========================
# AUDIT LOG CONFIGURATION
# ========================
AUDITLOG_INCLUDE_TRACKING_MODELS = ('iwm.Product', 'iwm.Order', 'iwm.NewsletterSubscriber', 'iwm.Coupon')

# ========================
# EXPORT CONFIGURATION
# ========================
IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_FORMATS = ['xlsx', 'csv', 'json']  # Supported export formats
