# Generated by Django 5.1.7 on 2025-10-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
    ]
