# Generated by Django 5.1.4 on 2026-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iwm", "0003_order_sender_number_alter_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_charge_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash_on_delivery", "Cash on Delivery"),
                    ("bkash", "bKash"),
                    ("nagad", "Nagad"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
