# Generated by Django 5.1.4 on 2026-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iwm", "0004_order_delivery_charge_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_payment_method",
            field=models.CharField(
                blank=True,
                choices=[("bkash", "bKash"), ("nagad", "Nagad")],
                max_length=20,
                null=True,
            ),
        ),
    ]
