# Generated by Django 5.1.4 on 2025-02-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwm', '0006_alter_review_rating_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/colors/'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/colors/'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/colors/'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_4_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/colors/'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_5_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/colors/'),
        ),
    ]
