# Generated by Django 5.1.4 on 2025-03-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iwm', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
    ]
