# Generated by Django 5.1.4 on 2026-04-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iwm", "0008_replace_payment_status_with_state"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="order",
            new_name="iwm_order_created_2c401b_idx",
            old_name="iwm_order_created_32e14d_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="iwm_order_order_s_c2ac40_idx",
            old_name="iwm_order_order_s_ab0fae_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="iwm_order_payment_f964d9_idx",
            old_name="iwm_order_payment_a1304c_idx",
        ),
    ]
