# Generated by Django 5.1.4 on 2026-04-09 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iwm",
            "0009_rename_iwm_order_created_32e14d_idx_iwm_order_created_2c401b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="iwm.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_usage_released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_sender_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="inventory_restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
