# Generated by Django 5.1.4 on 2025-03-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwm', '0010_userverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
