# Generated by Django 5.1.4 on 2026-05-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iwm", "0011_order_db_guards_and_product_stock_constraints"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="order",
            new_name="iwm_order_order_s_9465e1_idx",
            old_name="iwm_order_order_s_927712_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="iwm_order_payment_5f6c2e_idx",
            old_name="iwm_order_payment_5ce184_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="iwm_product_created_1a97ba_idx",
            old_name="iwm_product_created_4ce980_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="iwm_product_stock_6dca53_idx",
            old_name="iwm_product_stock_8ca593_idx",
        ),
    ]
