# Generated by Django 5.1.4 on 2025-03-15 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwm', '0011_userprofile_bio_userprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_1_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_2_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_3_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_4_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_5_image',
        ),
        migrations.CreateModel(
            name='MoreImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more_images', to='iwm.product')),
            ],
        ),
    ]
