# Generated by Django 5.1.4 on 2026-05-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iwm",
            "0012_rename_iwm_order_order_s_927712_idx_iwm_order_order_s_9465e1_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_1", models.CharField(max_length=100)),
                ("title_2", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=300)),
                ("image", models.ImageField(upload_to="promo_banners/")),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="order_transaction_id_ci_unique",
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="order_delivery_transaction_id_ci_unique",
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
