# Generated by Django 5.1.4 on 2026-05-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iwm", "0014_add_buying_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="buying_price",
            field=models.PositiveIntegerField(),
        ),
    ]
