# Generated by Django 5.1.4 on 2025-03-17 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwm', '0015_category_featurereason_product_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='feature_reasons',
        ),
        migrations.AddField(
            model_name='product',
            name='feature_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_products', to='iwm.featurereason'),
        ),
    ]
