# Generated by Django 5.1.4 on 2026-05-27 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iwm", "0016_alter_review_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "Cash on Delivery"),
                    ("bkash", "bKash"),
                    ("nagad", "Nagad"),
                    ("walk_in", "Walk-in Purchase"),
                ],
                default="cash_on_delivery",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="iwm.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["phone"], name="iwm_order_phone_2cd522_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["transaction_id"], name="iwm_order_transac_c5500a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["delivery_transaction_id"], name="iwm_order_deliver_9adbe4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["idempotency_key"], name="iwm_order_idempot_2e5394_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("transaction_id", models.F("delivery_transaction_id")),
                        _negated=True,
                    ),
                    ("transaction_id", ""),
                    ("transaction_id__isnull", True),
                    _connector="OR",
                ),
                name="prevent_duplicate_transaction_ids_in_order",
            ),
        ),
    ]
