# Generated by Django 5.1.4 on 2025-03-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iwm', '0016_remove_product_feature_reasons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurereason',
            old_name='name',
            new_name='Reason',
        ),
        migrations.RemoveField(
            model_name='featurereason',
            name='description',
        ),
    ]
