# Generated by Django 5.1.4 on 2026-05-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iwm", "0017_alter_order_payment_method_alter_product_tags_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="prevent_duplicate_transaction_ids_in_order",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="iwm_order_phone_2cd522_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="iwm_order_transac_c5500a_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="iwm_order_deliver_9adbe4_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="iwm_order_idempot_2e5394_idx",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "Cash on Delivery"),
                    ("bkash", "bKash"),
                    ("nagad", "Nagad"),
                ],
                default="cash_on_delivery",
                max_length=20,
            ),
        ),
    ]
