# Generated by Django 5.1.4 on 2026-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iwm", "0020_remove_moreimages_and_main_color_help"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_amount",
            field=models.PositiveIntegerField(
                blank=True, help_text="Fixed discount amount", null=True
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_percent",
            field=models.PositiveIntegerField(
                blank=True, help_text="Percentage discount", null=True
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(
                default=0, help_text="0 means unlimited usage"
            ),
        ),
    ]
