# Generated by Django 5.1.7 on 2025-03-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwm', '0020_alter_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
