# Generated by Django 5.1.4 on 2026-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwm', '0024_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number displayed first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Slider',
                'verbose_name_plural': 'Homepage Sliders',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='iwm_coupon_is_acti_a4fe3d_idx',
            old_name='iwm_coupon_active_validto_idx',
        ),
        migrations.RenameIndex(
            model_name='newslettersubscriber',
            new_name='iwm_newslet_is_acti_815c32_idx',
            old_name='iwm_newsletter_active_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='iwm_product_is_feat_c084b7_idx',
            old_name='iwm_product_is_feat_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='iwm_review_created_ecedda_idx',
            old_name='iwm_review_created_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='iwm_review_product_e9dcc0_idx',
            old_name='iwm_review_product_date_idx',
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum discount cap for percentage coupons (e.g. 20% OFF up to Tk 50)', null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
