# Generated by Django 5.1.4 on 2026-06-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iwm", "0026_remove_order_access_pin_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="max_uses_per_phone",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum successful uses per normalized phone number. Blank means unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="long_description",
            field=models.TextField(
                blank=True,
                help_text="Rich HTML product details shown lower on the product page.",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                help_text="Short plain-text description shown near the product title."
            ),
        ),
    ]
